Repository VDP-noclip/noclip, pull requests merged in 2022-12, with the labels that each got.

#147 jump one time when key is pressed
  Assets/Code/Scripts/NoclipRealityManagement/RealityMovementCalibration.cs
Labels: player, DEMO FEATURE

#123 Feedback menu added... linked to our Google Form!
  Assets/Art/UI/Fonts/CODE Bold.otf
  Assets/Art/UI/Fonts/CODE Bold.otf.meta
  Assets/Art/UI/Icons/Choice1.png
  Assets/Art/UI/Icons/Choice1.png.meta
  Assets/Art/UI/Icons/Choice2.png
  Assets/Art/UI/Icons/Choice2.png.meta
  Assets/Art/UI/Icons/Choice3.png
  Assets/Art/UI/Icons/Choice3.png.meta
  Assets/Art/UI/Icons/Choice4.png
  Assets/Art/UI/Icons/Choice4.png.meta
  Assets/Art/UI/Icons/Choice5.png
  Assets/Art/UI/Icons/Choice5.png.meta
  Assets/Art/UI/Icons/NextButton.png
  Assets/Art/UI/Icons/NextButton.png.meta
  Assets/Art/UI/Icons/RectangleVote.png
  Assets/Art/UI/Icons/RectangleVote.png.meta
  Assets/Code/Scripts/Feedbacks.meta
  Assets/Code/Scripts/Feedbacks/Nunito-Light SDF.asset
  Assets/Code/Scripts/Feedbacks/Nunito-Light SDF.asset.meta
  Assets/Code/Scripts/Feedbacks/Nunito-Light.ttf
  Assets/Code/Scripts/Feedbacks/Nunito-Light.ttf.meta
  Assets/Code/Scripts/Feedbacks/SendToGoogle.cs
  Assets/Code/Scripts/Feedbacks/SendToGoogle.cs.meta
  Assets/Code/Scripts/MenuManagement/PauseMenuController.cs
  Assets/Level/Prefabs/Feedback.meta
  Assets/Level/Prefabs/Feedback/FeedbackContainer 1 Variant.prefab
  Assets/Level/Prefabs/Feedback/FeedbackContainer 1 Variant.prefab.meta
  Assets/Level/Prefabs/Feedback/FeedbackContainer 1.prefab
  Assets/Level/Prefabs/Feedback/FeedbackContainer 1.prefab.meta
  Assets/Level/Prefabs/Feedback/FeedbackContainer.prefab
  Assets/Level/Prefabs/Feedback/FeedbackContainer.prefab.meta
  Assets/Level/Prefabs/Feedback/InputField (TMP).prefab
  Assets/Level/Prefabs/Feedback/InputField (TMP).prefab.meta
  Assets/Level/Prefabs/Feedback/MultipleChoice.prefab
  Assets/Level/Prefabs/Feedback/MultipleChoice.prefab.meta
  Assets/Level/Scenes/Common/PauseMenuUI_v2.unity
  Assets/Level/Scenes/Feedback.meta
  Assets/Level/Scenes/Feedback/Feedback.unity
  Assets/Level/Scenes/Feedback/Feedback.unity.meta
  Assets/Level/Scenes/Menu_0.unity
Labels: high priority, ui/ux, design, DEMO FEATURE

#151 Bufgix: avoid enabling noclip if we spam noclipKey
  Assets/Code/Scripts/NoclipRealityManagement/NoclipManager.cs
Labels: bug, DEMO FEATURE

#174 Main menu + pause menu ready for our demo!
  Assets/Art/UI/Icons/saving....png
  Assets/Art/UI/Icons/saving....png.meta
  Assets/Code/Scripts/MenuManagement/PauseMenuController.cs
  Assets/Level/Prefabs/Feedback/FeedbackContainer 1.prefab
  Assets/Level/Scenes/Common/PauseMenuUI_v2.unity
  Assets/Level/Scenes/Menu_0.unity
Labels: feature, polishing, ui/ux, design, DEMO FEATURE

#177 Final menu tweaks
  Assets/Code/Scripts/MenuManagement/PauseMenuController.cs
  Assets/Level/Scenes/Common/PauseMenuUI_v2.unity
  Assets/Level/Scenes/Menu_0.unity
Labels: polishing, ui/ux, DEMO FEATURE

#189 Fixed calibrations and removed 60fps cap
  Assets/Code/Scripts/LevelManagement/GameManager.cs
  Assets/Code/Scripts/NoclipRealityManagement/RealityMovementCalibration.cs
  Assets/Level/Prefabs/Player/AllPlayer.prefab
  Assets/Level/Scenes/Common/SceneWithPlayer.unity
Labels: high priority, player

#207 Fixed audio slider consistency
  Assets/Code/Scripts/MenuManagement/LoadPrefs.cs
  Assets/Code/Scripts/MenuManagement/MenuController.cs
  Assets/Code/Scripts/MenuManagement/PauseMenuController.cs
  Assets/Level/Scenes/Common/PauseMenuUI_v2.unity
  Assets/Level/Scenes/Menu_0.unity
Labels: ui/ux, audio

#209 Loading screen implementation
  Assets/Code/ScriptableObjects/LoadingSceneOption.asset
  Assets/Code/ScriptableObjects/LoadingSceneOption.asset.meta
  Assets/Code/ScriptableObjects/LoadingSceneOption.cs
  Assets/Code/ScriptableObjects/LoadingSceneOption.cs.meta
  Assets/Code/Scripts/LevelManagement/GameManager.cs
  Assets/Code/Scripts/LoadingManagement.meta
  Assets/Code/Scripts/LoadingManagement/LoadingScreenController.cs
  Assets/Code/Scripts/LoadingManagement/LoadingScreenController.cs.meta
  Assets/Level/Scenes/0_Main.unity
  Assets/Level/Scenes/Common/LoadingScreen.unity
  Assets/Level/Scenes/Common/LoadingScreen.unity.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: feature, ui/ux, levels

#212 Crosshair Audio Cue + Hints / Dialogue overhaul
  Assets/Audio/UI/mixkit-electric-ticking-counter-1054.wav
  Assets/Audio/UI/mixkit-electric-ticking-counter-1054.wav.meta
  Assets/Code/Scripts/GuiManagement/TimeLeftInPuzzleController.cs
  Assets/Code/Scripts/GuiManagement/TutorialController.cs
  Assets/Code/Scripts/NoclipRealityManagement/NoclipManager.cs
  Assets/Code/Scripts/PlayerManagement/TimeConstraints.cs
  Assets/Level/Scenes/Common/GUI.unity
  Assets/Level/Scenes/Common/LoadingScreen.unity
Labels: feature, polishing, ui/ux, audio

#221 Fix stop/resume timer based on noclip state
  Assets/Code/Scripts/PlayerManagement/TimeConstraints.cs
Labels: bug
