Repository VDP-noclip/noclip, pull requests merged in 2022-11, with the labels that each got.

#38 Save feature added and various tweaks
  Assets/Code/Scripts/LevelManagement/FinishLevel.cs
  Assets/Code/Scripts/LevelManagement/FinishLevel.cs.meta
  Assets/Code/Scripts/MenuManagement/LoadPrefs.cs
  Assets/Code/Scripts/MenuManagement/MenuController.cs
  Assets/Code/Scripts/NoclipRealityManagement.meta
  Assets/Code/Scripts/NoclipRealityManagement/NoclipManager.cs
  Assets/Code/Scripts/NoclipRealityManagement/NoclipManager.cs.meta
  Assets/Code/Scripts/NoclipRealityManagement/NoclipMovement.cs
  Assets/Code/Scripts/NoclipRealityManagement/NoclipMovement.cs.meta
  Assets/Code/Scripts/NoclipRealityManagement/NoclipObjController.cs
  Assets/Code/Scripts/NoclipRealityManagement/NoclipObjController.cs.meta
  Assets/Code/Scripts/NoclipRealityManagement/RealityMovement.cs
  Assets/Code/Scripts/NoclipRealityManagement/RealityMovement.cs.meta
  Assets/Code/Scripts/PlayerManagement.meta
  Assets/Code/Scripts/PlayerManagement/CameraManager.cs
  Assets/Code/Scripts/PlayerManagement/CameraManager.cs.meta
  Assets/Code/Scripts/PlayerManagement/MouseLook.cs
  Assets/Code/Scripts/PlayerManagement/MouseLook.cs.meta
  Assets/Code/Scripts/PlayerManagement/MoveCamera.cs
  Assets/Code/Scripts/PlayerManagement/MoveCamera.cs.meta
  Assets/Code/Scripts/PlayerManagement/RealityPlayerCollisions.cs
  Assets/Code/Scripts/PlayerManagement/RealityPlayerCollisions.cs.meta
  Assets/Level/Prefabs/GoalPlatform.prefab
  Assets/Level/Prefabs/SpawnPlatform.prefab
  Assets/Level/Scenes/Menu_0.unity
  Assets/Level/Scenes/Scene_1.unity
  Assets/Level/Scenes/Scene_3_new_respawn_structure.unity
  Assets/Level/Scenes/Scene_slopy.unity
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/TagManager.asset
Labels: feature, polishing, levels, prefabs

#41 Fix checkpoint respawn
  Assets/Code/Scripts/LevelManagement/CheckpointController.cs
  Assets/Code/Scripts/LevelManagement/GameManager.cs
  Assets/Code/Scripts/LevelManagement/OutOfBoundsController.cs
  Assets/Code/Scripts/LevelManagement/OutOfBoundsController.cs.meta
  Assets/Code/Scripts/PlayerManagement/RealityPlayerCollisions.cs
  Assets/Level/Prefabs/Checkpoint.prefab
  Assets/Level/Scenes/Scene_3_new_respawn_structure.unity
  Assets/Level/Scenes/new_game_plus.unity
Labels: bug, urgent

#43 First implementation of complete noclip management: switch mesh render and camera
  Assets/Code/Scripts/NoclipRealityManagement/NoclipManager.cs
  Assets/Code/Scripts/NoclipRealityManagement/NoclipMovement.cs
  Assets/Code/Scripts/PlayerManagement/CameraManager.cs
  Assets/Code/Scripts/PlayerManagement/RealityPlayerCollisions.cs
  Assets/Level/Scenes/Scene_3_new_respawn_structure.unity
Labels: feature, high priority, levels

#44 Change hierarchy of allPlayer prefab
  Assets/Code/Scripts/NoclipRealityManagement/NoclipMovement.cs
  Assets/Code/Scripts/NoclipRealityManagement/RealityMovement.cs
  Assets/Code/Scripts/PlayerManagement/CameraManager.cs
  Assets/Code/Scripts/PlayerManagement/MouseLook.cs
  Assets/Level/Prefabs/Player/AllPlayer.prefab
  Assets/Level/Prefabs/Player/AllPlayer.prefab.meta
  Assets/Level/Scenes/Scene_1.unity
Labels: bug, prefabs

#60 Additive scenes organization
  Assets/Code/Scripts/NoclipRealityManagement/NoclipManager.cs
  Assets/Code/Scripts/Utils.meta
  Assets/Code/Scripts/Utils/AdditiveSceneLoader.cs
  Assets/Code/Scripts/Utils/AdditiveSceneLoader.cs.meta
  Assets/Code/Scripts/Utils/PuzzleManager.cs
  Assets/Code/Scripts/Utils/PuzzleManager.cs.meta
  Assets/Level/Prefabs/AreaManager.prefab
  Assets/Level/Prefabs/AreaManager.prefab.meta
  Assets/Level/Prefabs/Puzzles.meta
  Assets/Level/Prefabs/Puzzles/Puzzle-00-01.prefab
  Assets/Level/Prefabs/Puzzles/Puzzle-00-01.prefab.meta
  Assets/Level/Prefabs/Puzzles/Puzzle-00-02.prefab
  Assets/Level/Prefabs/Puzzles/Puzzle-00-02.prefab.meta
  Assets/Level/Scenes/Areas.meta
  Assets/Level/Scenes/Areas/Area_00.meta
  Assets/Level/Scenes/Areas/Area_00/Area_00.unity
  Assets/Level/Scenes/Areas/Area_00/Area_00.unity.meta
  Assets/Level/Scenes/Areas/Area_00/Environment_00.unity
  Assets/Level/Scenes/Areas/Area_00/Environment_00.unity.meta
  Assets/Level/Scenes/Common.meta
  Assets/Level/Scenes/Common/GUI.unity
  Assets/Level/Scenes/Common/GUI.unity.meta
  Assets/Level/Scenes/Common/SceneWithPlayer.unity
  Assets/Level/Scenes/Common/SceneWithPlayer.unity.meta
  Assets/Level/Scenes/Menu_0.unity
  Assets/Level/Scenes/Obsolete.meta
  Assets/Level/Scenes/Obsolete/Scene_1.unity
  Assets/Level/Scenes/Obsolete/Scene_1.unity.meta
  Assets/Level/Scenes/Obsolete/Scene_3_new_respawn_structure.unity
  Assets/Level/Scenes/Obsolete/Scene_3_new_respawn_structure.unity.meta
  Assets/Level/Scenes/Obsolete/Scene_slopy.unity
  Assets/Level/Scenes/Obsolete/Scene_slopy.unity.meta
  Assets/Level/Scenes/Obsolete/new_game_plus.unity
  Assets/Level/Scenes/Obsolete/new_game_plus.unity.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: feature, high priority, levels, prefabs

#61 PlayerPrefs.HasKey("masterInvertY") be like: I will ruin this man's whole career
  Assets/Code/Scripts/PlayerManagement/MouseLook.cs
  Assets/Code/Scripts/PlayerManagement/MoveCamera.cs
  Assets/Code/Scripts/PlayerManagement/MoveCamera.cs.meta
  Assets/Level/Prefabs/Player/AllPlayer.prefab
Labels: bug, high priority, urgent

#58 Minor improvements no clip objects and manager
  Assets/Code/Scripts/NoclipObjectControllers/BaseNoclipObjectController.cs
  Assets/Code/Scripts/NoclipObjectControllers/NoclipIntangibleController.cs
  Assets/Code/Scripts/NoclipObjectControllers/NoclipObjController.cs
  Assets/Code/Scripts/NoclipRealityManagement/NoclipManager.cs
Labels: polishing

#74 Small fix and additions in RealityMovement.cs
  Assets/Code/Scripts/NoclipRealityManagement/RealityMovement.cs
Labels: bug, player

#78 Bugfix: apply "Default" layer since the empty layer is not in the layers list
  Assets/Level/Prefabs/Puzzles/PuzzleComponents/ObjectsHolders/IntangibleNoclipObjectsHolder.prefab
Labels: bug

#79 Improve game manager and puzzle manager code
  Assets/Code/Scripts/LevelManagement/GameManager.cs
  Assets/Code/Scripts/Utils/PuzzleManager.cs
  Assets/Level/Prefabs/Puzzles/Puzzle_12.prefab
  Assets/Level/Prefabs/Puzzles/Puzzle_13.prefab
  Assets/Level/Scenes/0_Main.unity
Labels: polishing

#82 Move Cube_5 into the correct object holder (invisibleNoclipObjectHolder)
  Assets/Level/Prefabs/Puzzles/Puzzle_13.prefab
Labels: bug

#85 Minor: add 'invisible' keyword in the previously called "noclipObjects"
  Assets/Code/Scripts/NoclipObjectControllers/NoclipInvisibleObjController.cs
  Assets/Code/Scripts/NoclipObjectControllers/NoclipInvisibleObjController.cs.meta
  Assets/Level/Prefabs/Puzzles/PuzzleComponents/NoclipObjects/InvisibleNoclipObjects/NoclipInvisiblePlatform.prefab
  Assets/Level/Prefabs/Puzzles/PuzzleComponents/NoclipObjects/InvisibleNoclipObjects/NoclipInvisiblePlatform.prefab.meta
Labels: polishing, prefabs

#99 change MouseLook.cs without delta time
  Assets/Code/Scripts/PlayerManagement/MouseLook.cs
  Assets/Level/Prefabs/Player/AllPlayer.prefab
Labels: bug, player

#98 fix jump tentative
  Assets/Code/Scripts/NoclipRealityManagement/RealityMovementCalibration.cs
Labels: bug, player

#97 Add reality player feedback: headbob and footstep sound
  Assets/Audio/PlayerSound.meta
  Assets/Audio/PlayerSound/Footsteps.meta
  Assets/Audio/PlayerSound/Footsteps/Footsteps_1.wav
  Assets/Audio/PlayerSound/Footsteps/Footsteps_1.wav.meta
  Assets/Audio/PlayerSound/Footsteps/Footsteps_2.wav
  Assets/Audio/PlayerSound/Footsteps/Footsteps_2.wav.meta
  Assets/Audio/PlayerSound/Footsteps/Footsteps_3.wav
  Assets/Audio/PlayerSound/Footsteps/Footsteps_3.wav.meta
  Assets/Audio/PlayerSound/Footsteps/Footsteps_4.wav
  Assets/Audio/PlayerSound/Footsteps/Footsteps_4.wav.meta
  Assets/Audio/PlayerSound/Footsteps/Footsteps_5.wav
  Assets/Audio/PlayerSound/Footsteps/Footsteps_5.wav.meta
  Assets/Code/Scripts/NoclipRealityManagement/RealityMovement.cs
  Assets/Code/Scripts/NoclipRealityManagement/RealityMovementCalibration.cs
  Assets/Code/Scripts/NoclipRealityManagement/RealityMovementFeedbacks.cs
  Assets/Code/Scripts/NoclipRealityManagement/RealityMovementFeedbacks.cs.meta
  Assets/Level/Prefabs/Player/AllPlayer.prefab
Labels: feature, prefabs, player

#96 GUI evolution with event listeners
  Assets/Art/UI/GUI.meta
  Assets/Art/UI/GUI/Crosshair (1).png
  Assets/Art/UI/GUI/Crosshair (1).png.meta
  Assets/Code/POLIMIgameCollective.meta
  Assets/Code/POLIMIgameCollective/EVENTM-1.meta
  Assets/Code/POLIMIgameCollective/EVENTM-1/EventManager.cs
  Assets/Code/POLIMIgameCollective/EVENTM-1/EventManager.cs.meta
  Assets/Code/Scripts/NoclipRealityManagement/NoclipManager.cs
  Assets/Code/Scripts/PlayerManagement/RealityPlayerCollisions.cs
  Assets/Code/Scripts/TutorialManagement.meta
  Assets/Code/Scripts/TutorialManagement/TutorialController.cs
  Assets/Code/Scripts/TutorialManagement/TutorialController.cs.meta
  Assets/Level/Scenes/0_Main.unity
  Assets/Level/Scenes/Common/GUI.unity
Labels: feature, high priority, ui/ux

#102 Working mixer added
  Assets/Audio/Mixer.meta
  Assets/Audio/Mixer/NoclipMixer.mixer
  Assets/Audio/Mixer/NoclipMixer.mixer.meta
  Assets/Code/Scripts/MenuManagement/LoadPrefs.cs
  Assets/Code/Scripts/MenuManagement/MenuController.cs
  Assets/Level/Scenes/Menu_0.unity
Labels: feature, high priority, ui/ux

#103 Pause Settings mini PR
  Assets/Audio/Mixer/NoclipMixer.mixer
  Assets/Code/Scripts/MenuManagement/LoadPrefs.cs
  Assets/Code/Scripts/MenuManagement/LoadPrefsLevels.cs
  Assets/Code/Scripts/MenuManagement/MenuController.cs
  Assets/Code/Scripts/MenuManagement/PauseMenuController.cs
  Assets/Code/Scripts/PlayerManagement/MouseLook.cs
  Assets/Level/Scenes/Areas/Area_00.unity
  Assets/Level/Scenes/Common/GUI.unity
  Assets/Level/Scenes/Common/PauseMenuUI_v2.unity
  Assets/Level/Scenes/Menu_0.unity
Labels: polishing, ui/ux

#113 Create a separate enum: MovementState
  Assets/Code/Scripts/NoclipRealityManagement/MovementState.cs
  Assets/Code/Scripts/NoclipRealityManagement/MovementState.cs.meta
  Assets/Code/Scripts/NoclipRealityManagement/RealityMovement.cs
  Assets/Code/Scripts/NoclipRealityManagement/RealityMovementCalibration.cs
  Assets/Code/Scripts/NoclipRealityManagement/RealityMovementFeedbacks.cs
Labels: polishing

#119 Invert Y and mixer going rogue fixed
  Assets/Code/Scripts/MenuManagement/MenuController.cs
  Assets/Code/Scripts/MenuManagement/PauseMenuController.cs
  Assets/Code/Scripts/PlayerManagement/MouseLook.cs
  Assets/Level/Scenes/Areas/Area_00.unity
Labels: bug, player, DEMO FEATURE

#112 correct audio listeners and event managers
  Assets/Level/Prefabs/Managers.meta
  Assets/Level/Prefabs/Managers/AudioManager.prefab
  Assets/Level/Prefabs/Managers/AudioManager.prefab.meta
  Assets/Level/Prefabs/Managers/EventSystem.prefab
  Assets/Level/Prefabs/Managers/EventSystem.prefab.meta
  Assets/Level/Prefabs/Player/AllPlayer.prefab
  Assets/Level/Prefabs/Utils/CalibratePlayerGUI.prefab
  Assets/Level/Scenes/0_Main.unity
  Assets/Level/Scenes/Common/GUI.unity
  Assets/Level/Scenes/Common/PauseMenuUI_v2.unity
  Assets/Level/Scenes/Menu_0.unity
Labels: polishing

#120 Option to automatically return to body and improve tutorial messages
  Assets/Code/POLIMIgameCollective/EventManager.meta
  Assets/Code/POLIMIgameCollective/EventManager/EventManager.cs
  Assets/Code/POLIMIgameCollective/EventManager/EventManager.cs.meta
  Assets/Code/ScriptableObjects/NoclipOptions.cs
  Assets/Code/Scripts/NoclipRealityManagement/NoclipManager.cs
  Assets/Code/Scripts/NoclipRealityManagement/NoclipMovement.cs
  Assets/Code/Scripts/PlayerManagement/RealityPlayerCollisions.cs
  Assets/Code/Scripts/TutorialManagement/TutorialController.cs
  Assets/Level/Scenes/Common/GUI.unity
Labels: polishing, DEMO FEATURE

#121 Add method for solve the movement problem at the switch mode
  Assets/Code/Scripts/NoclipRealityManagement/RealityMovementCalibration.cs
  Assets/Code/Scripts/PlayerManagement/CameraManager.cs
Labels: bug

#129 Change reality player size
  Assets/Code/Scripts/NoclipRealityManagement/RealityMovementCalibration.cs
  Assets/Level/Prefabs/Player/AllPlayer.prefab
Labels: DEMO FEATURE

#125 Impose time limits and respawn when you loose
  Assets/Art/UI/GUI/RectangleVote.png
  Assets/Art/UI/GUI/RectangleVote.png.meta
  Assets/Code/Scripts/GuiManagement.meta
  Assets/Code/Scripts/GuiManagement/TimeLeftInPuzzleController.cs
  Assets/Code/Scripts/GuiManagement/TimeLeftInPuzzleController.cs.meta
  Assets/Code/Scripts/GuiManagement/TutorialController.cs
  Assets/Code/Scripts/GuiManagement/TutorialController.cs.meta
  Assets/Code/Scripts/LevelManagement/AnchorCheckpointController.cs
  Assets/Code/Scripts/LevelManagement/RespawningManager.cs
  Assets/Code/Scripts/PlayerManagement/RealityPlayerCollisions.cs
  Assets/Code/Scripts/PlayerManagement/TimeConstraints.cs
  Assets/Code/Scripts/PlayerManagement/TimeConstraints.cs.meta
  Assets/Level/Prefabs/Player/AllPlayer.prefab
  Assets/Level/Prefabs/Utils/CalibratePlayerGUI.prefab
  Assets/Level/Scenes/Areas/Area_00.unity
  Assets/Level/Scenes/Common/GUI.unity
Labels: feature, high priority, design, DEMO FEATURE

#138 Tizio-Spig/automatically return to body in noclip
  Assets/Code/ScriptableObjects/DefaultNoclipOptions.asset
  Assets/Code/ScriptableObjects/NoclipOptions.cs
  Assets/Code/Scripts/NoclipRealityManagement/NoclipManager.cs
  Assets/Code/Scripts/PlayerManagement/CameraManager.cs
  Assets/Code/Scripts/PlayerManagement/MouseLook.cs
  Assets/Code/Scripts/Utils/FadeIn2.cs
Labels: DEMO FEATURE
