Repository VDP-noclip/noclip, pull requests merged in 2023-01, with the labels that each got.

#225 Add blinking crossair
  Assets/Code/Scripts/GuiManagement/TimeLeftInPuzzleController.cs
  Assets/Level/Scenes/Common/GUI.unity
Labels: feature, beta-version

#227 Add increasing pitch
  Assets/Code/Scripts/GuiManagement/TimeLeftInPuzzleController.cs
Labels: feature, beta-version, audio

#239 fix gradient dialogues
  Assets/Code/Scripts/GuiManagement/TutorialController.cs
  Assets/Level/Scenes/Common/GUI.unity
Labels: bug, design

#238 bugfix of the walkalbe walls
  Assets/Code/Scripts/NoclipRealityManagement/RealityMovementCalibration.cs
Labels: bug, high priority, player

#254 Make develop error free again
  Assets/Code/Scripts/Utils/FadeIn2.cs
Labels: bug, high priority, urgent, DEMO FEATURE, beta-version

#243 Correct FadeIn of the loading screens
  Assets/Code/Scripts/LoadingManagement/LoadingScreenController.cs
  Assets/Level/Scenes/Common/LoadingScreen.unity
Labels: bug, ui/ux

#251 Image for dialogue in UI
  Assets/Art/UI/GUI/Tutorial.meta
  Assets/Art/UI/GUI/Tutorial/Movement.png
  Assets/Art/UI/GUI/Tutorial/Movement.png.meta
  Assets/Art/UI/GUI/Tutorial/WASD.png
  Assets/Art/UI/GUI/Tutorial/WASD.png.meta
  Assets/Code/POLIMIgameCollective/EventManager/TutorialDialogObject.cs
  Assets/Code/Scripts/GuiManagement/DialogueBoxController.cs
  Assets/Code/Scripts/GuiManagement/TutorialController.cs
  Assets/Level/Prefabs/GUI/Tutorial.meta
  Assets/Level/Prefabs/GUI/Tutorial/Jump.prefab
  Assets/Level/Prefabs/GUI/Tutorial/Jump.prefab.meta
  Assets/Level/Prefabs/GUI/Tutorial/Movement.prefab
  Assets/Level/Prefabs/GUI/Tutorial/Movement.prefab.meta
  Assets/Level/Prefabs/GUI/Tutorial/WASD.prefab
  Assets/Level/Prefabs/GUI/Tutorial/WASD.prefab.meta
  Assets/Level/Scenes/Areas/Area_00.unity
  Assets/Level/Scenes/Common/GUI.unity
Labels: feature, ui/ux

#257 Change the way in which we load playerprefs and use default values
  Assets/Code/ScriptableObjects/DefaultPlayerPrefs.asset
  Assets/Code/ScriptableObjects/DefaultPlayerPrefs.asset.meta
  Assets/Code/ScriptableObjects/DefaultPlayerPrefs.cs
  Assets/Code/ScriptableObjects/DefaultPlayerPrefs.cs.meta
  Assets/Code/Scripts/MenuManagement/LoadPrefs.cs
  Assets/Code/Scripts/MenuManagement/LoadPrefsLevels.cs
  Assets/Code/Scripts/MenuManagement/LoadPrefsLevels.cs.meta
  Assets/Code/Scripts/MenuManagement/MenuController.cs
  Assets/Code/Scripts/MenuManagement/PauseMenuController.cs
  Assets/Code/Scripts/PlayerManagement/FovManagement.cs
  Assets/Level/Prefabs/GUI/LoadPrefs.prefab
  Assets/Level/Prefabs/GUI/LoadPrefs.prefab.meta
  Assets/Level/Scenes/0_Main.unity
  Assets/Level/Scenes/Menu_0.unity
Labels: bug, polishing, ui/ux, audio

#259 Add _requiredPlayerPrefsVersion to delete all the playerPrefs if needed
  Assets/Code/Scripts/MenuManagement/LoadPrefs.cs
Labels: beta-version

#260 audio improvements
  Assets/Code/ScriptableObjects/AudioTracks.cs
  Assets/Code/ScriptableObjects/DefaultAudioTracks.asset
  Assets/Code/Scripts/Audio/AreaAudioSourceController.cs
  Assets/Code/Scripts/Audio/AudioChangeBoxController.cs
  Assets/Code/Scripts/Audio/AudioChangeBoxController.cs.meta
  Assets/Code/Scripts/NoclipRealityManagement/NoclipManager.cs
  Assets/Code/Scripts/Utils/FadeIn2.cs
  Assets/Level/Prefabs/AreaManager.prefab
  Assets/Level/Prefabs/Audio.meta
  Assets/Level/Prefabs/Audio/ChangeAudioSoundtrackTrigger.prefab
  Assets/Level/Prefabs/Audio/ChangeAudioSoundtrackTrigger.prefab.meta
  Assets/Level/Prefabs/Player/AllPlayer.prefab
  Assets/Level/Scenes/0_Main.unity
  Assets/Level/Scenes/Common/LoadingScreen.unity
Labels: bug, feature, audio

#262 add audio in dialogue
  Assets/Code/POLIMIgameCollective/EventManager/TutorialDialogObject.cs
  Assets/Code/Scripts/GuiManagement/DialogueBoxController.cs
  Assets/Code/Scripts/GuiManagement/TutorialController.cs
  Assets/Level/Scenes/Common/GUI.unity
Labels: feature, audio

#266 Postprocessing fix
  Assets/Code/Scripts/NoclipRealityManagement/NoclipManager.cs
  Assets/Level/Prefabs/PostProcessing/PostProcessingNoclip.prefab
  Assets/Level/Prefabs/PostProcessing/PostProcessingReality.prefab
  ProjectSettings/TagManager.asset
Labels: bug, beta-version

#264 Pause Menu updated + scaling issue fixed
  Assets/Art/UI/Icons/MenuNew/Fill.png
  Assets/Art/UI/Icons/MenuNew/Fill.png.meta
  Assets/Art/UI/Icons/MenuNew/PauseBackground.png
  Assets/Art/UI/Icons/MenuNew/SlashPause.png
  Assets/Art/UI/Icons/MenuNew/SlashPause.png.meta
  Assets/Art/UI/noclip_logo_blur.png
  Assets/Audio/UI/noclip_voice.wav
  Assets/Audio/UI/pause_voice.wav
  Assets/Audio/UI/pause_voice.wav.meta
  Assets/Code/Scripts/GuiManagement/AnimationsController.cs
  Assets/Code/Scripts/GuiManagement/AnimationsController.cs.meta
  Assets/Code/Scripts/GuiManagement/TutorialController.cs
  Assets/Code/Scripts/MenuManagement/MenuController.cs
  Assets/Code/Scripts/MenuManagement/PauseMenuController.cs
  Assets/Level/Scenes/Common/GUI.unity
  Assets/Level/Scenes/Common/LoadingScreen.unity
  Assets/Level/Scenes/Common/PauseMenuUI_v2.unity
  Assets/Level/Scenes/Menu_0.unity
  ProjectSettings/InputManager.asset
Labels: bug, ui/ux, design, beta-version

#240 Fix bug when we skip the loading screen with some specific keys
  Assets/Code/Scripts/LoadingManagement/LoadingScreenController.cs
Labels: bug

#269 Ultimate pause menu
  Assets/Art/UI/noclip_blurPause.png
  Assets/Art/UI/noclip_blurPause.png.meta
  Assets/Code/Scripts/GuiManagement/TutorialController.cs
  Assets/Code/Scripts/MenuManagement/LoadPrefs.cs
  Assets/Code/Scripts/MenuManagement/MenuController.cs
  Assets/Code/Scripts/NoclipRealityManagement/RealityMovement.cs
  Assets/Code/Scripts/PlayerManagement/MouseLook.cs
  Assets/Level/Scenes/Common/GUI.unity
  Assets/Level/Scenes/Common/PauseMenuUI_v2.unity
  Assets/Level/Scenes/Menu_0.unity
Labels: bug, polishing, ui/ux

#265 set audio volumes
  Assets/Audio/EnvironmentSounds/WaterfallSound.prefab
  Assets/Audio/Mixer/NoclipMixer.mixer
  Assets/Code/ScriptableObjects/DefaultPlayerPrefs.asset
  Assets/Code/ScriptableObjects/DefaultPlayerPrefs.cs
  Assets/Code/Scripts/LevelManagement/GameManager.cs
  Assets/Level/Prefabs/Player/AllPlayer.prefab
  Assets/Level/Scenes/Areas/Area_01_waterfall_sound.unity
Labels: polishing, audio

#279 add audio in loading screen
  Assets/Code/ScriptableObjects/LoadingSceneOption.asset
  Assets/Code/ScriptableObjects/LoadingSceneOption.cs
  Assets/Code/Scripts/LoadingManagement/LoadingScreenController.cs
  Assets/Level/Scenes/Common/LoadingScreen.unity
Labels: beta-version, audio

#276 Dialogue gradients
  Assets/Art/UI/Fonts/ChakraPetch-MediumItalic SDF.asset
  Assets/Code/Scripts/GuiManagement/TutorialController.cs
  Assets/Level/Scenes/Common/GUI.unity
Labels: polishing, ui/ux

#277 Properly update quality settings and fullscreen mode in menu GUI
  Assets/Code/Scripts/MenuManagement/LoadPrefs.cs
  Assets/Code/Scripts/MenuManagement/MenuController.cs
Labels: bug

#283 add final tutorial images
  Assets/Art/UI/GUI/Tutorial/Movement.png
  Assets/Art/UI/GUI/Tutorial/WASD.png
  Assets/Art/UI/GUI/Tutorial/camera.png
  Assets/Art/UI/GUI/Tutorial/camera.png.meta
  Assets/Art/UI/GUI/Tutorial/jump.png
  Assets/Art/UI/GUI/Tutorial/jump.png.meta
  Assets/Art/UI/GUI/Tutorial/noclip.png
  Assets/Art/UI/GUI/Tutorial/noclip.png.meta
  Assets/Level/Prefabs/GUI/Tutorial/Jump.prefab
  Assets/Level/Prefabs/GUI/Tutorial/Movement.prefab
  Assets/Level/Prefabs/GUI/Tutorial/RightMouseButton.prefab
  Assets/Level/Prefabs/GUI/Tutorial/WASD.prefab
  Assets/Level/Scenes/Common/GUI.unity
Labels: feature, design

#286 after the last scene the menu reappear
  Assets/Code/Scripts/LevelManagement/GameManager.cs
Labels: feature

#289 New background (YEASADSA) + controls/feedback revisited
  Assets/Art/Backgrounds/8bb14ef0-5f2e-4c13-b977-557ef57bc75e.png
  Assets/Art/Backgrounds/8bb14ef0-5f2e-4c13-b977-557ef57bc75e.png.meta
  Assets/Art/UI/Icons/Controls/GamepadControls.png
  Assets/Art/UI/Icons/Controls/KeyboardControls.png
  Assets/Art/UI/Icons/Controls/controls.png
  Assets/Art/UI/Icons/Controls/controls.png.meta
  Assets/Audio/UI/mixkit-electric-ticking-counter-1054.wav.asd
  Assets/Audio/UI/mixkit-electric-ticking-counter-1054.wav.asd.meta
  Assets/Level/Prefabs/Feedback/FeedbackContainer 1.prefab
  Assets/Level/Scenes/Common/PauseMenuUI_v2.unity
  Assets/Level/Scenes/Menu_0.unity
Labels: polishing, ui/ux

#290 new icon and splash image
  Assets/Art/Icon/SplashImage/PolimiGameCollective.png
  Assets/Art/Icon/SplashImage/PolimiGameCollective.png.meta
  Assets/Art/Icon/icon_final.png
  Assets/Art/Icon/icon_final.png.meta
  ProjectSettings/ProjectSettings.asset
Labels: design

#298 Micro fix for Pause Menu Controls
  Assets/Level/Scenes/Common/PauseMenuUI_v2.unity
Labels: polishing

#306 correct build settings
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/QualitySettings.asset
Labels: bug

#310 Cursor update
  Assets/Art/UI/Icons/cursor.png
Labels: polishing
